---
name: App-MultiUser
version: 0.0002
author:
  - 'Chad Granum <exodist7@gmail.com>'
abstract: Base framework for an application with users and roles.
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  DBD::SQLite: 1
  Test::Database: 1.07
  Test::Exception: 0
  Test::More: 0
requires:
  Carp: 0
  Data::Dumper: 0
  Fey: 0
  Fey::DBIManager: 0
  Fey::Loader: 0.11
  Fey::ORM: 0
  Module::Pluggable: 0
  Moose: 0
  Moose::Role: 0
  MooseX::ClassAttribute: 0
configure_requires:
  Module::Build: 0.35
provides:
  App::MultiUser:
    file: lib/App/MultiUser.pm
    version: 0.0002
  App::MultiUser::Account:
    file: lib/App/MultiUser/Account.pm
  App::MultiUser::Base:
    file: lib/App/MultiUser/Base.pm
  App::MultiUser::Cache:
    file: lib/App/MultiUser/Cache.pm
  App::MultiUser::DB:
    file: lib/App/MultiUser/DB.pm
  App::MultiUser::DB::EntityTable:
    file: lib/App/MultiUser/DB/EntityTable.pm
  App::MultiUser::DB::Handle:
    file: lib/App/MultiUser/DB/Handle.pm
  App::MultiUser::DB::Migration:
    file: lib/App/MultiUser/DB/Migration.pm
  App::MultiUser::DB::Migration::000InitialSchema:
    file: lib/App/MultiUser/DB/Migration/000InitialSchema.pm
  App::MultiUser::DB::Schema:
    file: lib/App/MultiUser/DB/Schema.pm
  App::MultiUser::Entity:
    file: lib/App/MultiUser/Entity.pm
  App::MultiUser::Entity::Property:
    file: lib/App/MultiUser/Entity/Property.pm
  App::MultiUser::Entity::Role:
    file: lib/App/MultiUser/Entity/Role.pm
  App::MultiUser::Permission:
    file: lib/App/MultiUser/Permission.pm
  App::MultiUser::Privilege:
    file: lib/App/MultiUser/Privilege.pm
  App::MultiUser::Privilege::Chain:
    file: lib/App/MultiUser/Privilege/Chain.pm
  App::MultiUser::Property:
    file: lib/App/MultiUser/Property.pm
  App::MultiUser::Role:
    file: lib/App/MultiUser/Role.pm
  App::MultiUser::Role::Membership:
    file: lib/App/MultiUser/Role/Membership.pm
  App::MultiUser::Test:
    file: lib/App/MultiUser/Test.pm
  App::MultiUser::Version:
    file: lib/App/MultiUser/Version.pm
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
